default:
  data_preparation:
    # Child birth date filters the cohort by age
    child_birth_date_min: "01/01/1982"
    child_birth_date_max: "31/12/1987"
    
    # The cohort should live continuously in NL in the following period
    child_live_start: "01/01/2014"
    child_live_end: "31/12/2018"
    
    # The cohort is allowed to be unregistered for this many days 
    # in this period
    child_live_slack_days: 3
    
    # Only cohort children with parents in this age range should be considered
    parent_min_age_at_birth: 15
    parent_max_age_at_birth: 50
    
    # Should we use the first address registration of a child as their childhood home?
    childhood_home_first: true
    # If we do not, then use the longest address registration before cutoff_year:
    childhood_home_cutoff_year: 18
    
    # Postal code link to homes will be considered on this target date
    postcode_target_date: "31/12/2019"
    # Neighbourhood geo link to homes will be considered on this target date
    gwb_target_date: "31/12/2019"
    
    # Income will be deflated to cpi_base_year euros.
    cpi_base_year: 2018
    
    # Parent income year range
    parent_income_year_min: 2006
    parent_income_year_max: 2010
    
    #  Child income year range
    child_income_year_min: 2017
    child_income_year_max: 2018

  data_analysis:
    test: "test"
    
  file_locations:
    # The data folder is the root folder of the cbs microdata tables
    data_folder: "cbsdata"
    # The scratch folder is used to write intermediate output
    scratch_folder: "scratch"
    
    # path to the cbs microdata
    gba_data: "Bevolking/GBAPERSOONTAB/GBAPERSOON2018TABV2.sav"
    gbaao_data: "Bevolking/GBAADRESOBJECTBUS/GBAADRESOBJECT2018V1.sav"
    kind_data: "Bevolking/KINDOUDERTAB/KINDOUDER2018TABV1.sav"
    postcode_data: "BouwenWonen/VSLPOSTCODEBUS/VSLPOSTCODEBUSV2020031.sav"
    vslgwb_data: "BouwenWonen/VSLGWBTAB/VSLGWB2019TAB03V1.sav"
    cpi_index_data: "resources/Consumentenprijzen__prijsindex_2015_100_07012021_123946.csv"
    
  


# Some file locations are different in the production environment at CBS
cbs:
  file_locations: 
    data_folder: "G:"

