default:
  data_preparation:
    # The name of the cohort
    cohort_name: "age21"
    
    # Child birth date filters the cohort by age
    child_birth_date_min: "01/01/1995"
    child_birth_date_max: "31/12/1999"

    # The cohort should live continuously in NL in the following period
    child_live_age: 21

    # The cohort is allowed to be unregistered for this many days 
    # in this period
    child_live_slack_days: 31

    # Should we use the address registration of a child on a specific age
    childhood_home_age: 15
    
   # Postal code link to homes will be considered on this target date
    postcode_target_date: "31/12/2023"
    # Neighbourhood geo link to homes will be considered on this target date
    gwb_target_date: "31/12/2023"
    # Corop geo link to homes will be considered on this target date
    corop_target_date: "31/12/2023"
    
    # Income will be deflated to cpi_base_year euros.
    cpi_base_year: 2020
    
    # Parent income year range
    parent_income_year_min: 2008
    parent_income_year_max: 2012
    
    # Parent wealth year range
    parent_wealth_year_min: 2008
    parent_wealth_year_max: 2012
    
    # eduation of students year range
    education_year_min: 2015
    education_year_max: 2020

    # primary school classroom year range
    primary_classroom_year_min: 2005
    primary_classroom_year_max: 2012

    # secondary school data year range
    secondary_classroom_year_min: 2007
    secondary_classroom_year_max: 2018
    
    # age at which we measure the outcomes
    outcome_age: 21

    
  file_locations:
    # The data folder is the root folder of the cbs microdata tables
    data_folder: "G:/"
    # The scratch folder is used to write intermediate output
    scratch_folder: "scratch/age21"
    
    # path to the cbs microdata
    gba_data: "Bevolking/GBAPERSOONTAB/2023/GBAPERSOON2023TABV1.sav"
    gbaao_data: "Bevolking/GBAADRESOBJECTBUS/GBAADRESOBJECT2023BUSV1.sav"
    kind_data: "Bevolking/KINDOUDERTAB/KINDOUDER2023TABV1.sav"
    postcode_data: "BouwenWonen/VSLPOSTCODEBUS/VSLPOSTCODEBUSV2024031.sav"
    vslgwb_data: "BouwenWonen/VSLGWBTAB/VSLGWB2023TAB03V1.sav"
    household_data: "Bevolking/GBAHUISHOUDENSBUS/GBAHUISHOUDENS2020BUSV1.sav"


    # resources
    cpi_index_data: "resources/Consumentenprijzen__prijsindex_2015_100_14112022_221558.xlsx"
    migration_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/LANDAKTUEELREFV11.SAV"
    corop_data: "K:/Utilities/HULPbestanden/GebiedeninNederland/Gemeenten en COROP vanaf 1981.xlsx"
    opleiding_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/OPLEIDINGSNRREFV34.SAV"
  
