default:
  data_preparation:
    # The name of the cohort
    cohort_name: "child_mortality"
    
    # Child birth date filters the cohort by age
    child_birth_date_min: "01/01/2008"
    child_birth_date_max: "31/12/2016"
    
    # Only cohort children with parents in this age range should be considered
    parent_min_age_at_birth: 15
    parent_max_age_at_birth: 50

   # Postal code link to homes will  be considered on this target date
    postcode_target_date: "31/12/2019"
    # Neighbourhood geo link to homes will be considered on this target date
    gwb_target_date: "31/12/2019"
    # Corop geo link to homes will be considered on this target date
    corop_target_date: "31/12/2019"
    
    # Income will be deflated to cpi_base_year euros.
    cpi_base_year: 2018
    
    # Parent income year range
    parent_income_year_min: 2014
    parent_income_year_max: 2018
    
    # censor income above this value
    income_censoring_value: 1200000
    
    # remove gestational age at given days
    cut_off_days_min: 168
    cut_off_days_max: 294
  
    # The parents education will be added to to the cohort
    education_parents: false
    
    # when we measure the household composition of the child
    childhood_home_age: 0
    
  file_locations:
    # The data folder is the root folder of the cbs microdata tables
    data_folder: "cbsdata"
    # The scratch folder is used to write intermediate output
    scratch_folder: "scratch/child_mortality"
    
    # path to the cbs microdata
    gba_data: "Bevolking/GBAPERSOONTAB/2018/GBAPERSOON2018TABV2.sav"
    gbaao_data: "Bevolking/GBAADRESOBJECTBUS/GBAADRESOBJECT2021BUSV1.sav"
    kind_data: "Bevolking/KINDOUDERTAB/2018/KINDOUDER2018TABV1.sav"
    postcode_data: "BouwenWonen/VSLPOSTCODEBUS/VSLPOSTCODEBUSV2022031.sav"
    vslgwb_data: "BouwenWonen/VSLGWBTAB/VSLGWB2022TAB03V2.sav"
    household_data: "Bevolking/GBAHUISHOUDENSBUS/GBAHUISHOUDENS2020BUSV1.sav"

  
    # resources
    cpi_index_data: "resources/Consumentenprijzen__prijsindex_2015_100_07012021_123946.csv"
    migration_data: "resources/LANDAKTUEELREF10.sav"
    corop_data: "resources/gemeenten_corop_1981.xlsx"
    opleiding_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/OPLEIDINGSNRREFV27.SAV"
    cto_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/ctorefv10.SAV"
  
