default:
  data_preparation:
    # The name of the cohort
    cohort_name: "elementary_school"
    
    # Child birth date filters the cohort by age
    child_birth_date_min: "01/01/2004"
    child_birth_date_max: "31/12/2005"
    
    # The cohort should live continuously in NL in the following period
    live_continuously: true
    child_live_start: "01/01/2016"
    child_live_end: "31/12/2018"
    
    # The cohort is allowed to be unregistered for this many days 
    # in this period
    child_live_slack_days: 31
    
    # Only cohort children with parents in this age range should be considered
    parent_min_age_at_birth: 15
    parent_max_age_at_birth: 50
    
    # Should we use the first address registration of a child as their childhood home?
    childhood_home_first: false
    
     # Should we use the first address registration of a child on a specific date
    childhood_home_date: true
    childhood_home_year: "2015-12-31"
    
     # Should we use the first address registration of a child at 31 december of the year of birth?
    childhood_home_birthyear: false
    
    # If we do not, then use the longest address registration before cutoff_year:
    childhood_home_cutoff_year: 18
    
    # Postal code link to homes will be considered on this target date
    postcode_target_date: "31/12/2019"
    # Neighbourhood geo link to homes will be considered on this target date
    gwb_target_date: "31/12/2019"
    
    # Income will be deflated to cpi_base_year euros.
    cpi_base_year: 2018
    
    # Parent income year range
    parent_income_year_min: 2014
    parent_income_year_max: 2018
    
    # censor income above this value
    income_censoring_value: 1200000

    # elementary school outcome year range
    elementary_school_year_min: 2014
    elementary_school_year_max: 2018

    
  file_locations:
    # The data folder is the root folder of the cbs microdata tables
    data_folder: "G:/"
    # The scratch folder is used to write intermediate output
    scratch_folder: "scratch/elementary_school"
    
    # path to the cbs microdata
    gba_data: "Bevolking/GBAPERSOONTAB/2018/GBAPERSOON2018TABV2.sav"
    gbaao_data: "Bevolking/GBAADRESOBJECTBUS/GBAADRESOBJECT2019BUSV1.sav"
    kind_data: "Bevolking/KINDOUDERTAB/2018/KINDOUDER2018TABV1.sav"
    postcode_data: "BouwenWonen/VSLPOSTCODEBUS/VSLPOSTCODEBUSV2021031.sav"
    vslgwb_data: "BouwenWonen/VSLGWBTAB/VSLGWB2021TAB03V1.sav"

    # resources
    cpi_index_data: "resources/Consumentenprijzen__prijsindex_2015_100_07012021_123946.csv"
    migration_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/LANDAKTUEELREFV10.SAV"
    corop_data: "K:/Utilities/Code_Listings/Gebieden in Nederland/Gemeenten en COROP vanaf 1981.xlsx"
    advice_data: "resources/vo_advisering.xlsx"
    advice_data_sheet: "table"
