default:
  data_preparation:
    # The name of the cohort
    cohort_name: "main"
    
    # Child birth date filters the cohort by age
    child_birth_date_min: "01/01/1981"
    child_birth_date_max: "31/12/1985"

    # The cohort should live continuously in NL in the following period
    child_live_start: 34
    child_live_end: 35

    # The cohort is allowed to be unregistered for this many days 
    # in this period
    child_live_slack_days: 31
    
    # take the address registration on a specific age
    childhood_home_age: 15
    
    # Postal code link to homes will be considered on this target date
    postcode_target_date: "31/12/2023"
    # Neighbourhood geo link to homes will be considered on this target date
    gwb_target_date: "31/12/2023"
    # Corop geo link to homes will be considered on this target date
    corop_target_date: "31/12/2023"
    
    # Income will be deflated to cpi_base_year euros.
    cpi_base_year: 2020
    
    # Parent income year range
    parent_income_year_min: 2003
    parent_income_year_max: 2007
    
    # Parent wealth year range
    parent_wealth_year_min: 2006
    parent_wealth_year_max: 2010
    
    # child age at which we measure the outcome
    outcome_age: 35
    
    # The parents education will be added to to the cohort
    education_parents: false
    
    # Child income year range
    child_income_year_min: 2015
    child_income_year_max: 2020
    
    # Child outome year range
    child_outcome_year_min: 2016
    child_outcome_year_max: 2020
    
    # gifts received year range
    gifts_dat_start: 2007
    gifts_dat_end: 2020
    gifts_year_start: 26
    gifts_year_end: 35
    
    
  file_locations:
    # The data folder is the root folder of the cbs microdata tables
    data_folder: "G:/"
    # The scratch folder is used to write intermediate output
    scratch_folder: "scratch/main"
    
    # path to the cbs microdata
    gba_data: "Bevolking/GBAPERSOONTAB/2018/GBAPERSOON2018TABV2.sav"
    gbaao_data: "Bevolking/GBAADRESOBJECTBUS/GBAADRESOBJECT2023BUSV1.sav"
    kind_data: "Bevolking/KINDOUDERTAB/KINDOUDER2023TABV1.sav"
    postcode_data: "BouwenWonen/VSLPOSTCODEBUS/VSLPOSTCODEBUSV2024031.sav"
    vslgwb_data: "BouwenWonen/VSLGWBTAB/VSLGWB2023TAB03V1.sav"
    secm_data: "InkomenBestedingen/SECMBUS/SECMBUS2021V1.SAV"
    property_data: "BouwenWonen/EIGENDOMTAB/EIGENDOM2018TABV3.sav"
    household_data: "Bevolking/GBAHUISHOUDENSBUS/GBAHUISHOUDENS2020BUSV1.sav"
    birth_dat: "Bevolking/GBAPERSOONTAB/2021/GBAPERSOON2021TABV1.sav"
    woon_data: "BouwenWonen/LEVCYCLWOONNIETWOONBUS/LEVCYCLWOONNIETWOONBUSV2023122.sav"

    # resources
    cpi_index_data: "resources/Consumentenprijzen__prijsindex_2015_100_14112022_221558.xlsx"
    migration_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/LANDAKTUEELREFV11.SAV"
    corop_data: "K:/Utilities/HULPbestanden/GebiedeninNederland/Gemeenten en COROP vanaf 1981.xlsx"

    
